AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template for Kinesis Stream'
Parameters:
  RoleName:
    Type: String
    Default: 'kinesis-role'
    Description: 'The name of the IAM role for Kinesis stream.'
  StreamName:
    Type: String
    Default: 'kinesis-stream'
    Description: 'The name of the Kinesis stream.'
  StreamMode:
    Type: String
    Default: 'ON_DEMAND'
    AllowedValues:
      - PROVISIONED
      - ON_DEMAND
    Description: 'The mode of the Kinesis stream.'
  RetentionPeriodHours:
    Type: Number
    Default: 24
    Description: 'The retention period for the Kinesis stream in hours.'
  MetricsOption:
    Type: String
    Default: 'ALL'
    AllowedValues:
      - ALL
      - NONE
    Description: 'The metrics option for the Kinesis stream.'
  Project:
    Type: String
    Default: 'kinesis-project'
    Description: 'The project name.'
Resources:
  MyKinesisStreamRole: 
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: kinesis.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: KinesisStreamPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "kinesis: *"
                Resource: !GetAtt MyKinesisStream.Arn
              - Effect: Allow
                Action:
                  - "sts:AssumeRole"
                Resource: "*"
  MyKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      DesiredShardLevelMetrics: 
        - !Ref MetricsOption
      Name: !Ref StreamName
      RetentionPeriodHours: !Ref RetentionPeriodHours
      StreamModeDetails: 
        StreamMode: !Ref StreamMode
      Tags:
        - Key: project
          Value: !Ref Project
      RoleARN: !GetAtt MyKinesisStreamRole.Arn
        
