AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infraestructura base para streaming con Kinesis + Lambda + Timestream'
Parameters:
  StreamName:
    Type: String
    Default: 'kinesis-stream'
    Description: 'The name of the Kinesis stream.'
  StreamMode:
    Type: String
    Default: 'ON_DEMAND'
    AllowedValues:
      - PROVISIONED
      - ON_DEMAND
    Description: 'The mode of the Kinesis stream.'
  RetentionPeriodHours:
    Type: Number
    Default: 24
    Description: 'The retention period for the Kinesis stream in hours.'
  MetricsOption:
    Type: String
    Default: 'ALL'
    AllowedValues:
      - ALL
      - NONE
    Description: 'The metrics option for the Kinesis stream.'
  Project:
    Type: String
    Default: 'kinesis-project'
    Description: 'The project name.'


Resources:
  ### 🔹 Kinesis Stream
  DataStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Ref StreamName
      ShardCount: 1
      RetentionPeriodHours: !Ref RetentionPeriodHours
      StreamModeDetails:
        StreamMode: !Ref StreamMode

  ### 🔹 Timestream Database
  TimestreamDatabase:
    Type: AWS::Timestream::Database
    Properties:
      DatabaseName: RealTimeDB

  ### 🔹 Timestream Table
  TimestreamTable:
    Type: AWS::Timestream::Table
    Properties:
      DatabaseName: !Ref TimestreamDatabase
      TableName: MetricsTable
      RetentionProperties:
        MemoryStoreRetentionPeriodInHours: 24
        MagneticStoreRetentionPeriodInDays: 7

  ### 🔹 IAM Role para Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaKinesisTimestreamRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaKinesisExecutionRole
        - arn:aws:iam::aws:policy/AmazonTimestreamFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  ### 🔹 Lambda Function (placeholder)
  StreamProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: StreamProcessor
      Runtime: python3.9
      Handler: app.lambda_handlers.stream_processor.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: mi-bucket-lambdas
        S3Key: function.zip 

  ### 🔹 Event Source Mapping (Kinesis → Lambda)
  LambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt DataStream.Arn
      FunctionName: !Ref StreamProcessorLambda
      StartingPosition: LATEST

        
