AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infraestructura base para streaming con Kinesis + Lambda + Timestream'
Parameters:
  StreamName:
    Type: String
    Default: 'binance-trades'
    Description: 'The name of the Kinesis stream.'
  StreamMode:
    Type: String
    Default: 'ON_DEMAND'
    AllowedValues:
      - PROVISIONED
      - ON_DEMAND
    Description: 'The mode of the Kinesis stream.'
  RetentionPeriodHours:
    Type: Number
    Default: 24
    Description: 'The retention period for the Kinesis stream in hours.'
  MetricsOption:
    Type: String
    Default: 'ALL'
    AllowedValues:
      - ALL
      - NONE
    Description: 'The metrics option for the Kinesis stream.'
  Project:
    Type: String
    Default: 'kinesis-project'
    Description: 'The project name.'


Resources:

  ### 🔹 Kinesis Stream
  DataStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Ref StreamName
      RetentionPeriodHours: !Ref RetentionPeriodHours
      StreamModeDetails:
        StreamMode: !Ref StreamMode



  ### 🔹 Lambda Function (placeholder)
  StreamProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: StreamProcessor
      Runtime: python3.9
      Handler: app.lambda_handlers.kinesis_to_dynamo.lambda_handler
      Role: !ImportValue LambdaExecutionRoleArn
      Code:
        S3Bucket: !ImportValue LambdaS3BucketName
        S3Key: kinesis_dynamo_${{ github.sha }}.zip

  ### 🔹 Event Source Mapping (Kinesis → Lambda)
  LambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt DataStream.Arn
      FunctionName: !Ref StreamProcessorLambda
      StartingPosition: LATEST

  ### 🔹 DynamoDB Table
  BinanceTradesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BinanceTrades
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tradeId
          AttributeType: N
        - AttributeName: pair
          AttributeType: S
      KeySchema:
        - AttributeName: tradeId
          KeyType: HASH
        - AttributeName: pair
          KeyType: RANGE
      Tags:
        - Key: Project
          Value: !Ref Project
  
  ### 🔹 Grafana Workspace
  ManagedGrafanaWorkspace:
    Type: AWS::Grafana::Workspace
    Properties:
      AccountAccessType: CURRENT_ACCOUNT
      AuthenticationProviders:
        - AWS_SSO
      PermissionType: SERVICE_MANAGED
      Name: !Sub "${Project}-grafana"
      Role: !ImportValue GrafanaRoleArn